-- MIGRATION SCRIPT
-- Database Type: DBType{type='mysql', urlScheme='jdbc:', dialect='org.hibernate.dialect.MySQLDialect', driverClass='com.mysql.jdbc.Driver'}
-- App Name: dynamictests
-- Database: testdynamic
-- Created At: 03-Apr-2020 10:59:03.UTC
-- Script Version: 2.1
-- -----------------------------------------------------------------
-- USER SQL SCRIPT