-- MIGRATION SCRIPT
-- Database Type: DBType{type='mysql', urlScheme='jdbc:', dialect='org.hibernate.dialect.MySQLDialect', driverClass='com.mysql.jdbc.Driver'}
-- App Name: dynamictests
-- Database: indextest
-- Created At: 14-Apr-2020 06:17:15.UTC
-- Script Version: 11.1
-- -----------------------------------------------------------------
-- USER SQL SCRIPT