/*Copyright (c) 2020-2021 fico.com All Rights Reserved.
 This software is the confidential and proprietary information of fico.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with fico.com*/
package com.fico.dmp.indextest.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;

import com.fico.dmp.indextest.models.query.SdsdRequest;

@Service
public class IndextestQueryExecutorServiceImpl implements IndextestQueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(IndextestQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("indextestWMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(value = "indextestTransactionManager")
    @Override
    public Integer executeSdsd(SdsdRequest sdsdRequest) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQueryForUpdate("sdsd", params);
    }

}